name: Stop EKS Node Group & RDS in AWS

on:
  workflow_dispatch:
  schedule:
    # Runs "At 08:00 PM on every day-of-week from Monday through Friday. Below time is mentioned in UTC time zone" (see https://crontab.guru)
    - cron: '30 14 * * 1-5'

jobs:
  stop-resources:
    name: Stop EKS nodegroup & RDS
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: non-prod
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.BAHMNI_AWS_ID }}
          aws-secret-access-key: ${{ secrets.BAHMNI_AWS_SECRET }}
          aws-region: ap-south-1
          role-to-assume: ${{ secrets.BAHMNI_INFRA_ADMIN_ROLE }}
          role-duration-seconds: 1200  # 20 mins
          role-session-name: BahmniInfraAdminSession
      - name: Stop EKS Node for ${{ env.ENVIRONMENT }} Cluster
        run: |
          aws eks update-nodegroup-config  \
          --cluster-name=bahmni-cluster-${{ env.ENVIRONMENT }}  \
          --nodegroup-name=node-group-${{ env.ENVIRONMENT }}  \
          --scaling-config minSize=0,maxSize=1,desiredSize=0  > /dev/null 2>&1

      - name: Stop ${{ env.ENVIRONMENT }} RDS Instance
        run: |
          aws rds stop-db-instance --db-instance-identifier bahmni-rds-${{ env.ENVIRONMENT }} > /dev/null 2>&1

      - name: Post Deployment Status To Slack
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":":white_check_mark:  Hello, EKS Node Group & RDS Instance stopped for the day"}' ${{ secrets.SLACK_WEBHOOK_URL }}

