name: Validate and Deploy to AWS

on:
  push:
    branches: [ BAH-1564 ]

jobs:
  terrascan_job:
    runs-on: ubuntu-latest
    name: terrascan-action
    container:
        image: accurics/terrascan
        options: --user root
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # - name: Run Terrascan
        
        # run: docker run accurics/terrascan
          # curl -L "$(curl -s https://api.github.com/repos/accurics/terrascan/releases/latest | grep -o -E "https://.+?_Darwin_x86_64.tar.gz")" > terrascan.tar.gz &&\
          # tar -xf terrascan.tar.gz terrascan && rm terrascan.tar.gz &&\
          # install terrascan /usr/local/bin && rm terrascan &&\
          # terrascan
      - name: Terrascan
        run: |
          terrascan init &&\
          terrascan scan
