name: Validate and Deploy to AWS

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'

jobs:
  terrascan:
    name: Terrascan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Terrascan
        run: brew install terrascan
      - name: Terrascan scan and validate
        run: ./terrascan/terrascan.sh
  
  tflint:
    name: TFLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1
      - name: TFLint
        run: ./tflint/tflint.sh
  tfsec:
    name: TFSec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install TFSec
        run: brew install tfsec
      - name: TFSec
        run: ./tfsec/tfsec.sh

  tfvalidate:
    name: Terraform Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Terraform Validate
        run: ./terraform/tf-validate.sh

  tfapply:
    name: Terraform Apply
    needs: [ terrascan, tflint, tfsec, tfvalidate ]
    if: ${{ (needs.terrascan.result == 'success') && (needs.tflint.result == 'success') && (needs.tfvalidate.result == 'success') && (needs.tfsec.result == 'success') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install eksctl
        run: brew install weaveworks/tap/eksctl
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.BAHMNI_AWS_ID }}
          aws-secret-access-key: ${{ secrets.BAHMNI_AWS_SECRET }}
          aws-region: ap-south-1
          role-to-assume: ${{ secrets.BAHMNI_INFRA_ADMIN_ROLE }}
          role-duration-seconds: 1200  # 20 mins
          role-session-name: BahmniInfraAdminSession
      - name: Provision shared resources
        run: |
          cd terraform/shared/
          terraform init -backend-config=../config.s3.tfbackend
          terraform apply -auto-approve
      - name: Provision resources for dev
        run: |
          cd terraform/environment/dev/
          terraform init -backend-config=../../config.s3.tfbackend
          terraform apply -auto-approve
          echo "CLUSTER_NAME=$(terraform output -raw eks_cluster_name)" >> $GITHUB_ENV
          echo "READ_ONLY_ACCESS_ROLE_ARN=$(terraform output -raw eks_read_only_access_role_arn)" >> $GITHUB_ENV
      - name: Setup User Access for Cluster
        run: |
          aws eks update-kubeconfig --name $CLUSTER_NAME
          kubectl apply -f k8s-rbac/read-only.yaml
          eksctl create iamidentitymapping \
          --cluster $CLUSTER_NAME \
          --arn $READ_ONLY_ACCESS_ROLE_ARN \
          --group read-only-access-group \
          --username assume-role-user \
          --no-duplicate-arns

  slack-workflow-status:
    name: Notify on Slack
    if: ${{ always() }}
    needs: [ tfapply ]
    runs-on: ubuntu-latest
    env:
      STATUS: ${{ (needs.tfapply.result == 'success') && 'success' || 'failure' }}
    steps:
      - name: Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ env.STATUS }}
          fields: message,author,workflow,repo 
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
