name: Validate and Deploy to AWS

on:
  push:
    branches: [ BAH-1564 ]

jobs:
  terrascan:
    name: terrascan
    runs-on: ubuntu-latest
    # container:
    #     image: accurics/terrascan
    #     options: --user root
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Terrascan
        run: brew install terrascan
      - name: Terrascan scan
        run: terrascan scan | tee scan_results
      - name: Validate Scan Results
        run: ./validate.sh
