name: Validate and Deploy to AWS

on:
  push:
    branches: [ BAH-1564 ]

jobs:
  terrascan:
    name: Terrascan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Terrascan
        run: brew install terrascan
      - name: Terrascan scan and validate
        run: ./terrascan/terrascan.sh
