name: Validate and Deploy to AWS

on:
  push:
    branches: [ main ]

jobs:
  terrascan:
    name: Terrascan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Terrascan
        run: brew install terrascan
      - name: Terrascan scan and validate
        run: ./terrascan/terrascan.sh
  
  tflint:
    name: TFLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1
      - name: TFLint
        run: ./tflint/tflint.sh
  tfsec:
    name: TFSec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install TFSec
        run: brew install tfsec
      - name: TFSec
        run: ./tfsec/tfsec.sh

  tfvalidate:
    name: Terraform Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Terraform Validate
        run: ./terraform/tf-validate.sh

  tfapply:
    name: Terraform Apply
    needs: [ terrascan, tflint, tfsec, tfvalidate ]
    if: ${{ (needs.terrascan.result == 'success') && (needs.tflint.result == 'success') && (needs.tfvalidate.result == 'success') && (needs.tfsec.result == 'success') }}
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.BAHMNI_AWS_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.BAHMNI_AWS_SECRET }}
      AWS_DEFAULT_REGION: ${{ secrets.BAHMNI_AWS_REGION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Provision shared resources
        run: |
          cd terraform/shared/
          terraform init -backend-config=../config.s3.tfbackend
          terraform apply -auto-approve
      - name: Provision resources for dev
        run: |
          cd terraform/environment/dev/
          terraform init -backend-config=../../config.s3.tfbackend
          terraform apply -auto-approve
      - name: Authorize kubectl with EKS
        run: aws eks update-kubeconfig --name $(terraform output -raw eks_cluster_name)
      - name: Install Nginx Ingress
        run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.2/deploy/static/provider/aws/deploy.yaml
      - name: Set Ingress DNS as SSM Parameter
        run: |
          INGRESS_DNS=$(kubectl get services --namespace ingress-nginx ingress-nginx-controller --output jsonpath='{.status.loadBalancer.ingress[0].hostname}')
          aws ssm put-parameter \
          --name "/dev/ingress/dns" \
          --value "$INGRESS_DNS" \
          --type String \
          --overwrite


  slack-workflow-status:
    name: Notify on Slack
    if: ${{ always() }}
    needs: [ tfapply ]
    runs-on: ubuntu-latest
    env:
      STATUS: ${{ (needs.tfapply.result == 'success') && 'success' || 'failure' }}
    steps:
      - name: Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ env.STATUS }}
          fields: message,author,workflow,repo 
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
