name: Validate and Deploy to AWS

on:
  push:
    branches: [ main ]

jobs:
  terrascan:
    name: Terrascan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Terrascan
        run: brew install terrascan
      - name: Terrascan scan and validate
        run: ./terrascan/terrascan.sh

  tflint:
    name: TFLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1
      - name: TFLint
        run: ./tflint/tflint.sh
  tfsec:
    name: TFSec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install TFSec
        run: brew install tfsec
      - name: TFSec
        run: ./tfsec/tfsec.sh

  slack-workflow-status:
    name: Notify on Slack
    if: ${{ always() }}
    needs: [ terrascan, tflint, tfsec ]
    runs-on: ubuntu-latest
    env:
      STATUS: ${{ (needs.terrascan.result == 'success') && (needs.tflint.result == 'success') && (needs.tfsec.result == 'success') && 'success' || 'failure' }}
    steps:
      - name: Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ env.STATUS }}
          fields: message,author,workflow,repo 
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
