name: Validate and Deploy to AWS

on:
  push:
    branches: [ BAH-1564 ]

jobs:
  terrascan_job:
    runs-on: ubuntu-latest
    name: terrascan-action
    container:
        image: accurics/terrascan
        options: --user root
    steps:
      - run: cat /etc/os-release
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Terrascan
        run: terrascan scan | tee scan_results.txt
      - name: setup python
        run: |
          apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python &&\
          python3 -m ensurepip &&\
          pip3 install --no-cache --upgrade pip setuptools
      - name: execute py script # run the run.py to get the latest data
        run: |
          python validate.py